js: add transformResultUrl callback
jameslittle230/stork pull request #274
Opened 2022-03-22 23:59 UTC by ArsenArsen

Transforming result URLs allows the user to build sites that are relocatable rather anchored on the site root (for instance, by prepending the resulting URL with the relative path to the root directory).

I'm sure other uses exist too, but this is what I need it for.

Thanks

2022-03-23 00:00 UTC, jameslittle230 commented
Can you give a sample code snippet of how you'd use this API?

2022-03-23 00:13 UTC, ArsenArsen commented
```js
    stork.register("stuff", rootPath + "searchidx.st", {
        "onQueryUpdate": onQueryUpdate,
        "onResultsHidden": onResultsHidden,
        "transformResultUrl": a => rootPath + a.substr(1),
    });
```

2022-03-23 15:19 UTC, ArsenArsen commented
Ah - a release happened at almost the exact same time I did this; stellar coincidence.

I rebased on top of the new release; I think the addition of a new feature makes this 1.5.0, do correct me if I'm wrong, though.

2022-03-23 23:06 UTC, jameslittle230 requested changes
Two nits, but this looks great. Thanks for contributing and creating a changelog entry (and the rebase 😅).

I'll merge once you make the two nit changes!

2022-03-23 23:06 UTC, jameslittle230 commented on changelog.md
> +- Add `transformResultUrl` callback to allow transforming search result URLs
```suggestion
- Adds the Javascript registration option `transformResultUrl`, which, when set, transforms search result URLs from what's described in the search index to what gets output in the DOM.
```

2022-03-23 23:19 UTC, ArsenArsen commented on js/config.ts
> +  transformResultUrl: a => a,
that was the haskell developer in me talking :P

2022-03-24 00:27 UTC, jameslittle230 approved these changes

2022-03-24 01:10 UTC, merged